steps:
  - label: ":golang: Build"
    command: go build
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml
          env:
            - GOOS=linux
            - GOARCH=amd64
